// Este campo es CLAVE para diferenciar en el listado y en el PDV
const initialListItem = [
  // --- Productos (Uniformes y Accesorios) ---
  {
    key: "1",
    id: 1,
    denominacion: "Pantalón Escolar Gris Talle 10",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 50,
    codigo_barras: "7798001001019",
    precio: 9500.0,
  },
  {
    key: "2",
    id: 2,
    denominacion: "Chomba Blanca Algodón Talle 14",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 75,
    codigo_barras: "7798001001026",
    precio: 5200.5,
  },
  {
    key: "3",
    id: 3,
    denominacion: "Pollera Tableada Azul Marino Talle S",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 30,
    codigo_barras: "7798001001033",
    precio: 7800.0,
  },
  {
    key: "4",
    id: 4,
    denominacion: "Sweater Lana Escolar Talle M",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 45,
    codigo_barras: "7798001001040",
    precio: 12500.99,
  },
  {
    key: "5",
    id: 5,
    denominacion: "Medias de Algodón Blancas (Pack x3)",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 120,
    codigo_barras: "7798001001057",
    precio: 1800.0,
  },
  {
    key: "6",
    id: 6,
    denominacion: "Camisa Cuadros Secundaria Talle L",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 60,
    codigo_barras: "7798001001064",
    precio: 8900.5,
  },
  {
    key: "7",
    id: 7,
    denominacion: "Pantalón Jogging Deportivo Talle 8",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 90,
    codigo_barras: "7798001001071",
    precio: 6500.0,
  },
  {
    key: "8",
    id: 8,
    denominacion: "Buzo Capucha Frisa Colegio X Talle 16",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 40,
    codigo_barras: "7798001001088",
    precio: 14900.0,
  },
  {
    key: "9",
    id: 9,
    denominacion: "Escudo Termoadhesivo Colegio Y",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 250,
    codigo_barras: "7798001001095",
    precio: 550.0,
  },
  {
    key: "10",
    id: 10,
    denominacion: "Corbata Escolar Rayada",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 80,
    codigo_barras: "7798001001101",
    precio: 2990.0,
  },
  {
    key: "11",
    id: 11,
    denominacion: "Remera Educación Física Talle XL",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 55,
    codigo_barras: "7798001001118",
    precio: 4100.0,
  },
  {
    key: "12",
    id: 12,
    denominacion: "Botón de Repuesto (Pack x10)",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 300,
    codigo_barras: "7798001001125",
    precio: 350.0,
  },
  {
    key: "13",
    id: 13,
    denominacion: "Short Deportivo Negro Talle P",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 70,
    codigo_barras: "7798001001132",
    precio: 4800.0,
  },
  {
    key: "14",
    id: 14,
    denominacion: "Cinturón de Cuero Negro",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 50,
    codigo_barras: "7798001001149",
    precio: 3999.0,
  },
  {
    key: "15",
    id: 15,
    denominacion: "Mochila Reforzada Clásica",
    telefono: "N/A",
    tipo_item: "PRODUCTO",
    stock_actual: 25,
    codigo_barras: "7798001001156",
    precio: 15500.0,
  },

  // --- Servicios ---
  {
    key: "16",
    id: 16,
    denominacion: "Servicio de Bordado de Nombre (por prenda)",
    telefono: "N/A",
    tipo_item: "SERVICIO",
    stock_actual: 0,
    codigo_barras: null,
    precio: 1200.0,
  },
  {
    key: "17",
    id: 17,
    denominacion: "Arreglo de Talle Simple (Ej. dobladillo)",
    telefono: "N/A",
    tipo_item: "SERVICIO",
    stock_actual: 0,
    codigo_barras: null,
    precio: 800.0,
  },
  {
    key: "18",
    id: 18,
    denominacion: "Diseño Personalizado de Uniforme (Escuela Nueva)",
    telefono: "N/A",
    tipo_item: "SERVICIO",
    stock_actual: 0,
    codigo_barras: null,
    precio: 45000.0,
  },
  {
    key: "19",
    id: 19,
    denominacion: "Estampado de Logo Deportivo (por unidad)",
    telefono: "N/A",
    tipo_item: "SERVICIO",
    stock_actual: 0,
    codigo_barras: null,
    precio: 1500.0,
  },
  {
    key: "20",
    id: 20,
    denominacion: "Consultoría de Tallas a Domicilio",
    telefono: "N/A",
    tipo_item: "SERVICIO",
    stock_actual: 0,
    codigo_barras: null,
    precio: 3000.0,
  },
];

export { initialListItem };
