CREATE TABLE AdminCajaCierre (
  Id INT NOT NULL AUTO_INCREMENT,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  Saldo DECIMAL(12,2) NOT NULL,
  UsuarioId INT DEFAULT NULL,
  SucursalId INT DEFAULT NULL,
  OrganizacionId INT DEFAULT NULL,
  PRIMARY KEY (Id)
);
