CREATE TABLE FormaPago (
  Id INT NOT NULL AUTO_INCREMENT,
  OrganizacionId INT NOT NULL,
  Tipo VARCHAR(20) NOT NULL COMMENT 'Venta | Pago | Cobro',
  Nombre VARCHAR(100) NOT NULL,
  Sigla VARCHAR(2) NOT NULL,
  RequiereEntidad TINYINT(1) DEFAULT 0,
  ImpactaCaja TINYINT(1) DEFAULT 0,
  ImpactaCtaCte TINYINT(1) DEFAULT 0,
  Activo TINYINT(1) DEFAULT 1,
  PRIMARY KEY (Id)
);
