CREATE TABLE Organizacion (
  Id INT NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(150) NOT NULL,
  SucursalDefault INT DEFAULT NULL,
  TiposMovimiento JSON DEFAULT NULL,
  Activo TINYINT(1) DEFAULT 1,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
