CREATE TABLE UsuarioSistema (
  Id INT NOT NULL AUTO_INCREMENT,
  Username VARCHAR(50) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Mail VARCHAR(150) DEFAULT NULL,
  Nombre VARCHAR(150) DEFAULT NULL,
  Activo TINYINT(1) DEFAULT 1,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id),
  UNIQUE INDEX UQ_UsuarioSistema_Username (Username)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
