CREATE TABLE UsuarioSucursal (
  Id INT NOT NULL AUTO_INCREMENT,
  UsuarioId INT NOT NULL,
  SucursalId INT NOT NULL,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
