CREATE TABLE Permiso (
  Id INT NOT NULL AUTO_INCREMENT,
  RolId INT NOT NULL,
  Modulo VARCHAR(50) NOT NULL,
  Formulario VARCHAR(50) NOT NULL,
  Acciones JSON DEFAULT NULL,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
