CREATE TABLE Proveedor (
  Id BIGINT NOT NULL,
  Nro INT NOT NULL,
  Nombre VARCHAR(150) NOT NULL,
  Telefono VARCHAR(50) DEFAULT NULL,
  Activo TINYINT(1) DEFAULT 1,
  Saldo DECIMAL(12,2) DEFAULT 0,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
