CREATE TABLE FormaPago (
  Id INT NOT NULL AUTO_INCREMENT,
  OrganizacionId INT NOT NULL,
  Tipo VARCHAR(20) NOT NULL COMMENT 'Venta | Pago | Cobro',
  Nombre VARCHAR(100) NOT NULL,
  Sigla VARCHAR(10) NOT NULL,
  RequiereEntidad TINYINT(1) DEFAULT 0,
  ImpactaCaja TINYINT(1) DEFAULT 1,
  ImpactaCtaCte TINYINT(1) DEFAULT 0,
  Activo TINYINT(1) DEFAULT 1,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
