CREATE TABLE Rubro (
  Id INT NOT NULL AUTO_INCREMENT,
  OrganizacionId INT NOT NULL,
  Sigla VARCHAR(10) NOT NULL,
  Nombre VARCHAR(100) NOT NULL,
  Grupo VARCHAR(100) DEFAULT NULL,
  Activo TINYINT(1) DEFAULT 1,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
