CREATE TABLE Movimiento (
  Id BIGINT NOT NULL,
  Tipo VARCHAR(20) NOT NULL COMMENT 'Venta | Pago | Cobro | Ingreso | Retiro',
  Importe DECIMAL(12,2) NOT NULL,
  EntidadId BIGINT DEFAULT NULL,
  EntidadNombre VARCHAR(150) DEFAULT NULL,
  Fecha DATE DEFAULT NULL,
  Hora VARCHAR(10) DEFAULT NULL,
  UsuarioId INT DEFAULT NULL,
  SucursalId INT DEFAULT NULL,
  SaldoCtaCte DECIMAL(12,2) DEFAULT NULL,
  Observacion TEXT DEFAULT NULL,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
