CREATE TABLE LineItem (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  MovimientoId BIGINT NOT NULL,
  Importe DECIMAL(12,2) NOT NULL,
  RubroId INT DEFAULT NULL,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
