CREATE TABLE Cierre (
  Id BIGINT NOT NULL,
  Fecha DATE DEFAULT NULL,
  Hora VARCHAR(10) DEFAULT NULL,
  Saldo DECIMAL(12,2) NOT NULL,
  UsuarioId INT DEFAULT NULL,
  SucursalId INT DEFAULT NULL,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
