CREATE TABLE MovimientoFormaPago (
  Id BIGINT NOT NULL AUTO_INCREMENT,
  MovimientoId BIGINT NOT NULL,
  Nombre VARCHAR(100) NOT NULL,
  Importe DECIMAL(12,2) NOT NULL,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (Id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
