CREATE TABLE Usuarios (
  Id INT NOT NULL AUTO_INCREMENT,
  Username VARCHAR(50) NOT NULL,
  Password VARCHAR(255) NOT NULL,
  Mail VARCHAR(150) DEFAULT NULL,
  Nombre VARCHAR(150) DEFAULT NULL,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  Activo TINYINT(1) DEFAULT 1,
  PRIMARY KEY (Id)
);