CREATE TABLE RolPermisos (
  Id INT NOT NULL AUTO_INCREMENT,
  RolId INT NOT NULL,
  Modulo VARCHAR(50) NOT NULL,
  Formulario VARCHAR(50) NOT NULL,
  Acciones JSON DEFAULT NULL,
  PRIMARY KEY (Id)
);