CREATE TABLE Movimientos (
  Id INT NOT NULL AUTO_INCREMENT,
  Tipo VARCHAR(20) NOT NULL,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  ImporteTotal DECIMAL(12,2) NOT NULL,
  EntidadId INT DEFAULT NULL,
  EntidadNombre VARCHAR(150) DEFAULT NULL,
  UsuarioId INT DEFAULT NULL,
  SucursalId INT DEFAULT NULL,
  OrganizacionId INT DEFAULT NULL,
  Observacion TEXT DEFAULT NULL,
  PRIMARY KEY (Id)
);
