CREATE TABLE Proveedores (
  Id INT NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(150) NOT NULL,
  Telefono VARCHAR(50) DEFAULT NULL,
  Mail VARCHAR(150) DEFAULT NULL,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  Activo TINYINT(1) DEFAULT 1,
  PRIMARY KEY (Id)
);
