CREATE TABLE Rubros (
  Id INT NOT NULL AUTO_INCREMENT,
  OrganizacionId INT NOT NULL,
  Sigla VARCHAR(10) NOT NULL,
  Nombre VARCHAR(100) NOT NULL,
  Activo TINYINT(1) DEFAULT 1,
  PRIMARY KEY (Id)
);