CREATE TABLE Sucursales (
  Id INT NOT NULL AUTO_INCREMENT,
  OrganizacionId INT NOT NULL,
  Nombre VARCHAR(150) NOT NULL,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  Activo TINYINT(1) DEFAULT 1,
  PRIMARY KEY (Id)
);