CREATE TABLE Clientees (
  Id INT NOT NULL AUTO_INCREMENT,
  Nombre VARCHAR(150) NOT NULL,
  Telefono VARCHAR(50) DEFAULT NULL,
  Mail VARCHAR(150) DEFAULT NULL,
  CtaCteHabilitado TINYINT(1) DEFAULT 0,
  CtaCteImporteMaximo DECIMAL(12,2) DEFAULT NULL,
  CtaCtePlazoDias INT DEFAULT NULL,
  CtaCteSaldo DECIMAL(12,2) DEFAULT 0,
  FechaRegistro TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  Activo TINYINT(1) DEFAULT 1,
  PRIMARY KEY (Id)
);
