CREATE TABLE `Movimientos` (
  `Id` int NOT NULL AUTO_INCREMENT,
  `Tipo` varchar(50) NOT NULL,
  `Importe` decimal(18,2) NOT NULL DEFAULT '0.00',
  `FormaPago` varchar(50) NOT NULL DEFAULT 'Efectivo',
  `EntidadId` int DEFAULT NULL,
  `EntidadNombre` varchar(200) DEFAULT NULL,
  `EntidadNro` int DEFAULT NULL,
  `Fecha` date DEFAULT NULL,
  `Hora` varchar(10) DEFAULT NULL,
  `Usuario` varchar(100) DEFAULT NULL,
  `Activo` tinyint(1) DEFAULT '1',
  `OrganizacionId` int NOT NULL,
  `SucursalId` int DEFAULT NULL,
  `FechaRegistro` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`Id`),
  KEY `Idx_Movimientos_Fecha` (`Fecha`),
  KEY `Idx_Movimientos_Tipo` (`Tipo`),
  KEY `Idx_Movimientos_Activo` (`Activo`),
  KEY `Idx_Movimientos_Organizacion` (`OrganizacionId`),
  KEY `Idx_Movimientos_Sucursal` (`SucursalId`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
